server:
  port: 8086  # Port number for the API Gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/profiles/**
          filters:
            - RewritePath=/api/profiles/(?<segment>.*), /${segment}

        - id: list-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/lists/**
          filters:
            - RewritePath=/api/lists/(?<segment>.*), /${segment}

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<segment>.*), /${segment}

        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /${segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            allowCredentials: true

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
